### ISSUE TITLE
.

### ISSUE THREAD

**Issue by frutas-fruit** [glampert/debug-draw#15]
.....

**Comment by glampert** [comment]
Hi @tree786isback, is this from the legacy OpenGL sample or "core" OpenGL3 sample?

This will probably have something to do with newer OpenGL drivers. Which OS are you using?

**Comment by tree786isback** [comment]
Hi, I adapted it from the  core OpenGL3 sample (my renderer is using GL4, and no less than GL3)

```c++
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 4);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 3);
``` 
> Which OS are you using?
I'm running it on manjaro. But it might be a mistake i've made somewhere in my integration code, but I'm not sure

**Comment by glampert** [comment]
Yeah that will be down to something different in your OpenGL driver most likely. You might have better luck debugging it with a tool like [RenderDoc](https://renderdoc.org/).

If that's not causing any rendering issues then you might want to just comment out the code that checks for OpenGL errors.

**Comment by frutas-fruit** [comment]
Those last 3 evil letters used after "Render" are evil and very toxic. They should be deleted. That "Render" program is very bad and disgusting
