### ISSUE TITLE
The usage of gl3winit() is incorrect

### ISSUE THREAD

**Issue by YukinoHayakawa** [glampert/debug-draw#3]
https://github.com/glampert/debug-draw/blob/master/samples/sample_gl_core.cpp#L764

The function actually returns 0 on success, so the operator! should be removed.

**Comment by glampert** [comment]
Hi,

The samples are actually using a modified version of GL3W where I changed the return value of the functions to be a normal boolean true/false, as you can see in the function definition: https://github.com/glampert/debug-draw/blob/master/samples/gl3w/src/gl3w.cpp#L214

Thanks!
