### ISSUE TITLE
checkGLError() in the demo loops forever when error occurred

### ISSUE THREAD

**Issue by YukinoHayakawa** [glampert/debug-draw#4]

**Comment by glampert** [comment]
Hi,

Could you elabore on which platforms and under which circumstances you've noticed this problem? I was not able to repro this on OSX with either the GL core or legacy renderer after forcing an error every frame.

The correct behavior of glGetError is to clear the error flag to GL_NO_ERROR (guaranteed to be 0), so in a compliant implementation the checkGLError code should be correct. 

https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGetError.xhtml

Thanks!

**Comment by YukinoHayakawa** [comment]
Thank you for pointing that out. I'm quite new to OpenGL yet. I guess I messed something up and I actually cannot reproduce the issue anymore. Sorry for bothering.
