### ISSUE TITLE
LNK2005 every method or variable is already defined

### ISSUE THREAD

**Issue by vamidi** [glampert/debug-draw#8]
I added the interface and the define as the example now do I need to declare everything in the header?

**Comment by glampert** [comment]
Hi,

That probably means you have the macro `DEBUG_DRAW_IMPLEMENTATION` defined in every file that includes debug_draw.h. You should only have that macro defined in *a single .cpp file*. Other files including the debug draw header should not have that define.

**Comment by vamidi** [comment]
Thank you btw, going to implement soon. I was not familiar with c++ that much at the time!
